name: CI/CD with Newman and Qase

on: 
  workflow_dispatch:
jobs: 
  test: 
    defaults: 
      run: 
        working-directory: ./tests
    environment: staging
    name: "Run tests"
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Newman
      run: npm install -g newman

    - name: "Run tests"
      run: "newman run ReqresAPI.postman_collection.json -e Production.postman_environment.json"

    - name: Install Qase CLI
      run: npm install -g qase-cli

    - name: Upload test results to Qase
      run: qase run create --api-token ${{ secrets.QASE_API_TOKEN }} --project-code YOUR_PROJECT_CODE --suite-id YOUR_SUITE_ID --title "Test Run" --results-file test-results.xml