name: API Tests

on:
  push:
    branches:
      - main

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install -g newman qaseio-reporter

      - name: Run API tests
        run: newman run newman run ReqresAPI.postman_collection.json -e Production.postman_environment.json --reporters cli,qaseio --reporter-qaseio-apikey ${{ secrets.QASE_API_KEY }} --reporter-qaseio-project ${{ secrets.QASE_PROJECT_CODE }} --reporter-qaseio-suite ${{ secrets.QASE_SUITE_CODE }}