name:   CI/CD Test-Build

on: 
  workflow_dispatch:
jobs: 
  test: 
    defaults: 
      run: 
        working-directory: ./tests
    environment: staging
    name: "Run tests"
    runs-on: ubuntu-latest
    steps: 
      - 
        uses: actions/checkout@v2
      - 
        uses: actions/setup-node@v2
        with: 
          node-version: "18"
    
    - name: Install newman
      run: |
       npm install -g newman
       npm install -g newman-reporter-htmlextra

    - name: Make Directory for results
      run: mkdir -p testResults

    - name: Run POSTMAN collection
      run: |
       newman run ReqresAPI.postman_collection.json -e Production.postman_environment.json -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html --reporter-htmlextra-darkTheme  > testResults/runreport1.html

    - name: Output summary to console
      run: echo ${{ steps.run-newman.outputs.summary }}

    - name: Output the run Details
      uses: actions/upload-artifact@v2
      with: 
       name: API Test Reports
       path: testResults