name: Qase Tests
on: 
  workflow_dispatch:
jobs: 
  test: 
    defaults: 
      run: 
        working-directory: ./tests
    environment: staging
    name: "Run tests"
    runs-on: ubuntu-latest
    steps: 
      - 
        uses: actions/checkout@v2
      - 
        uses: actions/setup-node@v2
        with: 
          node-version: "18"
      - 
        name: "Install newman"
        run: "npm install -g newman"
      - 
        name: "Install newman reporter"
        run: "npm install -g newman-reporter-htmlextra"
      - 
        name: Run Newman tests
        run: |
          npm install -g newman
          newman run ReqresAPI.postman_collection.json \
            --environment=Production.postman_environment.json \
            --reporters cli,junit --reporter-junit-export=result.xml
      - 
        name: Upload test results to Qase
        uses: qaseio/action-upload-test-results@v1
        with:
          format: junit
          result-file: result.xml
          api-token: ${{ secrets.cdf3bcec02347a95bb451b9d21a03151bbf192ad812583f84b0e46df2bf61ac4}}
